eureka:
  instance:
    hostname: gateway
  client:
    serviceUrl:
      defaultZone: http://192.168.99.100:8010/eureka/
zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000