server:
  port: 8180
spring:
  profiles:
    active: beta
  application:
    name: zuul-gateway
zuul:
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken