/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 03-2月-2019 15:09:21 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `sc_menu` CASCADE
;

DROP TABLE IF EXISTS `sc_permission` CASCADE
;

DROP TABLE IF EXISTS `sc_role` CASCADE
;

DROP TABLE IF EXISTS `sc_role_menu` CASCADE
;

DROP TABLE IF EXISTS `sc_role_permission` CASCADE
;

DROP TABLE IF EXISTS `sc_user_info` CASCADE
;

DROP TABLE IF EXISTS `sc_user_role` CASCADE
;

/* Create Tables */

CREATE TABLE `sc_menu`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`uid` VARCHAR(50) NOT NULL,
	`code` VARCHAR(50) NOT NULL COMMENT '编码',
	`name` VARCHAR(50) NOT NULL COMMENT '名称',
	`link_url` VARCHAR(100) NOT NULL COMMENT '链接url',
	`type` VARCHAR(50) NOT NULL COMMENT '类型',
	`status` VARCHAR(50) NOT NULL COMMENT '状态',
	`create_user` VARCHAR(50) NOT NULL COMMENT '创建人',
	`create_time` DATETIME NOT NULL COMMENT '创建时间',
	`update_user` VARCHAR(50) NOT NULL COMMENT '最后修改人',
	`update_time` DATETIME NOT NULL COMMENT '最后修改时间',
	CONSTRAINT `PK_sc_menu` PRIMARY KEY (`id` ASC)
)
COMMENT = '系统菜单'

;

CREATE TABLE `sc_permission`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`uid` VARCHAR(50) NOT NULL,
	`code` VARCHAR(50) NOT NULL COMMENT '编码',
	`name` VARCHAR(50) NOT NULL COMMENT '名称',
	`status` VARCHAR(50) NOT NULL COMMENT '状态',
	`create_user` VARCHAR(50) NOT NULL COMMENT '创建人',
	`create_time` DATETIME NOT NULL COMMENT '创建时间',
	`update_user` VARCHAR(50) NOT NULL COMMENT '修改人',
	`update_time` DATETIME NOT NULL COMMENT '最后修改时间',
	CONSTRAINT `PK_sc_permission` PRIMARY KEY (`id` ASC)
)
COMMENT = '权限表'

;

CREATE TABLE `sc_role`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`uid` VARCHAR(50) NOT NULL,
	`code` VARCHAR(50) NOT NULL COMMENT '编码',
	`name` VARCHAR(50) NOT NULL COMMENT '名称',
	`status` VARCHAR(50) NOT NULL COMMENT '状态',
	`create_user` VARCHAR(50) NOT NULL COMMENT '创建人',
	`create_time` DATETIME NOT NULL COMMENT '创建时间',
	`update_user` VARCHAR(50) NOT NULL COMMENT '最后修改人',
	`update_time` DATETIME NOT NULL,
	CONSTRAINT `PK_sc_role` PRIMARY KEY (`id` ASC)
)
COMMENT = '角色表'

;

CREATE TABLE `sc_role_menu`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`uid` VARCHAR(50) NOT NULL,
	`role_code` VARCHAR(50) NOT NULL COMMENT '角色编码',
	`menu_code` VARCHAR(50) NOT NULL COMMENT '菜单编码',
	`create_user` VARCHAR(50) NOT NULL,
	`create_time` DATETIME NOT NULL,
	CONSTRAINT `PK_sc_role_menu` PRIMARY KEY (`id` ASC)
)
COMMENT = '角色菜单关系表'

;

CREATE TABLE `sc_role_permission`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`uid` VARCHAR(50) NOT NULL,
	`role_code` VARCHAR(50) NOT NULL COMMENT '角色编码',
	`permission_code` VARCHAR(50) NOT NULL COMMENT '权限编码',
	`create_user` VARCHAR(50) NOT NULL COMMENT '创建人',
	`create_time` DATETIME NOT NULL COMMENT '创建时间',
	CONSTRAINT `PK_sc_role_permission` PRIMARY KEY (`id` ASC)
)
COMMENT = '角色权限关系表'

;

CREATE TABLE `sc_user_info`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`uid` VARCHAR(50) NOT NULL,
	`code` VARCHAR(50) NOT NULL COMMENT '编码',
	`nick_name` VARCHAR(50) NULL COMMENT '昵称',
	`phone` VARCHAR(50) NOT NULL COMMENT '手机号码',
	`email` VARCHAR(50) NOT NULL COMMENT '电子邮箱',
	`type` VARCHAR(50) NOT NULL COMMENT '类型',
	`status` VARCHAR(50) NOT NULL COMMENT '状态',
	`create_user` VARCHAR(50) NOT NULL COMMENT '创建人',
	`create_time` DATETIME NOT NULL COMMENT '创建时间',
	`update_user` VARCHAR(50) NOT NULL COMMENT '最后修改人',
	`update_time` DATETIME NOT NULL,
	CONSTRAINT `PK_sc_user_info` PRIMARY KEY (`id` ASC)
)
COMMENT = '用户信息表'

;

CREATE TABLE `sc_user_role`
(
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`uid` VARCHAR(50) NOT NULL,
	`user_code` VARCHAR(50) NOT NULL,
	`role_code` VARCHAR(50) NOT NULL,
	`create_user` VARCHAR(50) NULL,
	`create_time` VARCHAR(50) NULL,
	CONSTRAINT `PK_sc_user_role` PRIMARY KEY (`id` ASC)
)
COMMENT = '用户角色关系表'

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `sc_menu` 
 ADD CONSTRAINT `code` UNIQUE (`code` ASC)
;

ALTER TABLE `sc_menu` 
 ADD INDEX `type_index` (`type` ASC)
;

ALTER TABLE `sc_menu` 
 ADD INDEX `status_index` (`status` ASC)
;

ALTER TABLE `sc_permission` 
 ADD CONSTRAINT `code_uniq` UNIQUE (`code` ASC)
;

ALTER TABLE `sc_permission` 
 ADD INDEX `status_index` (`status` ASC)
;

ALTER TABLE `sc_role` 
 ADD CONSTRAINT `code_uniq` UNIQUE (`code` ASC)
;

ALTER TABLE `sc_role` 
 ADD INDEX `status_index` (`status` ASC)
;

ALTER TABLE `sc_role_menu` 
 ADD CONSTRAINT `role_menu_uniq` UNIQUE (`role_code` ASC, `menu_code` ASC)
;

ALTER TABLE `sc_role_permission` 
 ADD CONSTRAINT `role_permission_uniq` UNIQUE (`role_code` ASC, `permission_code` ASC)
;

ALTER TABLE `sc_user_info` 
 ADD CONSTRAINT `code_uniq` UNIQUE (`code` ASC)
;

ALTER TABLE `sc_user_info` 
 ADD INDEX `phone_index` (`phone` ASC)
;

ALTER TABLE `sc_user_info` 
 ADD INDEX `type_index` (`type` ASC)
;

ALTER TABLE `sc_user_info` 
 ADD INDEX `status_index` (`status` ASC)
;

ALTER TABLE `sc_user_role` 
 ADD CONSTRAINT `user_role_uniq` UNIQUE (`user_code` ASC, `role_code` ASC)
;

SET FOREIGN_KEY_CHECKS=1 
;
