/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 15-2月-2019 11:31:02 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `pc_brand_info` CASCADE
;

DROP TABLE IF EXISTS `pc_category` CASCADE
;

DROP TABLE IF EXISTS `pc_label` CASCADE
;

DROP TABLE IF EXISTS `pc_product_info` CASCADE
;

DROP TABLE IF EXISTS `pc_product_pic` CASCADE
;

DROP TABLE IF EXISTS `pc_product_status` CASCADE
;

DROP TABLE IF EXISTS `pc_product_stock` CASCADE
;

DROP TABLE IF EXISTS `pc_product_type` CASCADE
;

DROP TABLE IF EXISTS `pc_produt_draft` CASCADE
;

DROP TABLE IF EXISTS `pc_sku_info` CASCADE
;

DROP TABLE IF EXISTS `pc_sku_pic` CASCADE
;

DROP TABLE IF EXISTS `pc_sku_status` CASCADE
;

DROP TABLE IF EXISTS `pc_sku_type` CASCADE
;

DROP TABLE IF EXISTS `pc_store_info` CASCADE
;

DROP TABLE IF EXISTS `pc_store_status` CASCADE
;

DROP TABLE IF EXISTS `pc_store_type` CASCADE
;

/* Create Tables */

CREATE TABLE `pc_brand_info`
(
	`uid` VARCHAR(50) NOT NULL,
	`code` VARCHAR(50) NOT NULL,
	`name` VARCHAR(50) NOT NULL COMMENT '品牌名称',
	`en_name` VARCHAR(50) NOT NULL COMMENT '品牌英文名称',
	`icon_url` VARCHAR(200) NOT NULL COMMENT '图标地址',
	`flag_enabled` INT NOT NULL DEFAULT 0 COMMENT '0 可用 1 不可用',
	`create_user` VARCHAR(50) NOT NULL,
	`create_time` DATETIME NOT NULL,
	`update_user` VARCHAR(50) NOT NULL,
	`update_time` DATETIME NOT NULL,
	CONSTRAINT `PK_pc_brand_info` PRIMARY KEY (`code` ASC)
)
COMMENT = '商品品牌表'

;

CREATE TABLE `pc_category`
(
	`uid` VARCHAR(50) NOT NULL,
	`code` VARCHAR(50) NOT NULL,
	`name` VARCHAR(50) NOT NULL,
	`flag_enabled` INT NULL DEFAULT 0 COMMENT '0 可用 1 不可用',
	`create_user` VARCHAR(50) NOT NULL,
	`create_time` DATETIME NOT NULL,
	`update_user` VARCHAR(50) NOT NULL,
	`update_time` DATETIME NOT NULL,
	CONSTRAINT `PK_pc_category` PRIMARY KEY (`code` ASC)
)
COMMENT = '商品分类表'

;

CREATE TABLE `pc_label`
(
	`uid` VARCHAR(50) NOT NULL,
	`code` VARCHAR(50) NOT NULL COMMENT '编码',
	`name` VARCHAR(50) NOT NULL,
	`flag_enabled` INT NULL DEFAULT 0 COMMENT '0 可用 1 不可用',
	`create_user` VARCHAR(50) NOT NULL,
	`create_time` DATETIME NOT NULL,
	`update_user` VARCHAR(50) NOT NULL,
	`update_time` DATETIME NOT NULL,
	CONSTRAINT `PK_pc_label` PRIMARY KEY (`code` ASC)
)
COMMENT = '商品标签表'

;

CREATE TABLE `pc_product_info`
(
	`uid` VARCHAR(50) NOT NULL,
	`code` VARCHAR(50) NOT NULL,
	`store_code` VARCHAR(50) NOT NULL COMMENT '卖家编码',
	`name` VARCHAR(50) NOT NULL,
	`en_name` VARCHAR(50) NOT NULL,
	`category_code` VARCHAR(50) NOT NULL COMMENT '商品分类编码',
	`brand_code` VARCHAR(50) NOT NULL COMMENT '商品品牌编码',
	`min_cost_price` DECIMAL(10,2) NOT NULL COMMENT '最小成本价',
	`max_cost_price` DECIMAL(10,2) NOT NULL COMMENT '最大成本价',
	`min_market_price` DECIMAL(10,2) NOT NULL COMMENT '最小市场价',
	`max_market_price` DECIMAL(10,2) NOT NULL COMMENT '最大市场价',
	`min_sell_price` DECIMAL(10,2) NOT NULL,
	`max_sell_price` DECIMAL(10,2) NOT NULL,
	`type` VARCHAR(50) NOT NULL COMMENT '类型',
	`status` VARCHAR(50) NOT NULL COMMENT '状态',
	`create_user` VARCHAR(50) NOT NULL,
	`create_time` DATETIME NOT NULL,
	`update_user` VARCHAR(50) NOT NULL,
	`update_time` DATETIME NOT NULL,
	CONSTRAINT `PK_pc_product_info` PRIMARY KEY (`code` ASC)
)
COMMENT = '商品信息表'

;

CREATE TABLE `pc_product_pic`
(
	`uid` VARCHAR(50) NOT NULL,
	`code` VARCHAR(50) NOT NULL COMMENT '商品编码',
	`product_code` VARCHAR(50) NOT NULL,
	`pic_url` VARCHAR(50) NOT NULL COMMENT '图片地址',
	`create_user` VARCHAR(50) NOT NULL,
	`create_time` DATETIME NOT NULL,
	CONSTRAINT `PK_pc_product_pic` PRIMARY KEY (`code` ASC)
)
COMMENT = '商品图片表'

;

CREATE TABLE `pc_product_status`
(
	`uid` VARCHAR(50) NOT NULL,
	`code` VARCHAR(50) NOT NULL,
	`name` VARCHAR(50) NOT NULL,
	`flag_enabled` INT NULL DEFAULT 0,
	`create_user` VARCHAR(50) NOT NULL,
	`create_time` DATETIME NOT NULL,
	`update_user` VARCHAR(50) NOT NULL,
	`update_time` DATETIME NOT NULL,
	CONSTRAINT `PK_pc_product_status` PRIMARY KEY (`code` ASC)
)
COMMENT = '商品状态表'

;

CREATE TABLE `pc_product_stock`
(
	`uid` VARCHAR(50) NOT NULL,
	`product_code` VARCHAR(50) NOT NULL COMMENT '商品编码',
	`sku_code` VARCHAR(50) NOT NULL,
	`before_stock` BIGINT NOT NULL COMMENT '修改前库存总数',
	`update_stock` BIGINT NOT NULL COMMENT '要修改的库存总数',
	`current_stock` BIGINT NOT NULL COMMENT '当前库存总数',
	`create_user` VARCHAR(50) NOT NULL,
	`create_time` DATETIME NOT NULL,
	`update_user` VARCHAR(50) NOT NULL,
	`update_time` DATETIME NOT NULL,
	CONSTRAINT `PK_pc_product_stock` PRIMARY KEY (`product_code` ASC, `sku_code` ASC)
)
COMMENT = '商品库存表'

;

CREATE TABLE `pc_product_type`
(
	`uid` VARCHAR(50) NOT NULL,
	`code` VARCHAR(50) NOT NULL COMMENT '编码',
	`name` VARCHAR(50) NOT NULL COMMENT '名称',
	`flag_enabled` INT NULL DEFAULT 0,
	`create_user` VARCHAR(50) NOT NULL,
	`create_time` DATETIME NOT NULL,
	`update_user` VARCHAR(50) NOT NULL,
	`update_time` DATETIME NOT NULL,
	CONSTRAINT `PK_pc_product_type` PRIMARY KEY (`code` ASC)
)
COMMENT = '商品类型表'

;

CREATE TABLE `pc_produt_draft`
(
	`uid` VARCHAR(50) NOT NULL,
	`code` VARCHAR(50) NOT NULL COMMENT '编码',
	`name` VARCHAR(50) NOT NULL COMMENT '名称',
	`en_name` VARCHAR(50) NOT NULL COMMENT '英文名称',
	`data` VARCHAR(1000) NOT NULL,
	`create_user` VARCHAR(50) NOT NULL,
	`create_time` DATETIME NOT NULL,
	`update_user` VARCHAR(50) NOT NULL,
	`update_time` DATETIME NOT NULL,
	CONSTRAINT `PK_pc_produt_draft` PRIMARY KEY (`code` ASC)
)
COMMENT = '商品草稿箱'

;

CREATE TABLE `pc_sku_info`
(
	`uid` VARCHAR(50) NOT NULL,
	`code` VARCHAR(50) NOT NULL COMMENT '编码',
	`product_code` VARCHAR(50) NOT NULL COMMENT '商品编码',
	`cost_price` DECIMAL(10,2) NOT NULL COMMENT '成本价',
	`sell_price` DECIMAL(10,2) NOT NULL COMMENT '销售价',
	`stock` BIGINT NOT NULL COMMENT '库存',
	`main_pic` VARCHAR(200) NOT NULL COMMENT 'sku主图',
	`type` VARCHAR(50) NOT NULL COMMENT '类型',
	`status` VARCHAR(50) NOT NULL COMMENT '状态',
	`create_user` VARCHAR(50) NOT NULL,
	`create_time` DATETIME NOT NULL,
	`update_user` VARCHAR(50) NOT NULL,
	`update_time` DATETIME NOT NULL,
	CONSTRAINT `PK_pc_sku_info` PRIMARY KEY (`code` ASC)
)
COMMENT = '商品SKU表'

;

CREATE TABLE `pc_sku_pic`
(
	`uid` VARCHAR(50) NOT NULL,
	`code` VARCHAR(50) NOT NULL COMMENT 'sku编码',
	`sku_code` VARCHAR(50) NOT NULL,
	`pic_url` VARCHAR(50) NOT NULL COMMENT '图片链接地址',
	`create_user` VARCHAR(50) NOT NULL,
	`create_time` DATETIME NOT NULL,
	CONSTRAINT `PK_pc_sku_pic` PRIMARY KEY (`code` ASC)
)
COMMENT = '商品SKU图片表'

;

CREATE TABLE `pc_sku_status`
(
	`uid` VARCHAR(50) NOT NULL,
	`code` VARCHAR(50) NOT NULL,
	`name` VARCHAR(50) NOT NULL,
	`flag_enabled` INT NULL DEFAULT 0 COMMENT '是否可用 0 可用 1 不可用',
	`create_user` VARCHAR(50) NOT NULL,
	`create_time` DATETIME NOT NULL,
	`update_user` VARCHAR(50) NOT NULL,
	`update_time` DATETIME NOT NULL,
	CONSTRAINT `PK_pc_sku_status` PRIMARY KEY (`code` ASC)
)

;

CREATE TABLE `pc_sku_type`
(
	`uid` VARCHAR(50) NOT NULL,
	`code` VARCHAR(50) NOT NULL,
	`name` VARCHAR(50) NOT NULL,
	`flag_enabled` INT NULL DEFAULT 0 COMMENT '0 可用 1 不可用',
	`create_user` VARCHAR(50) NOT NULL,
	`create_time` DATETIME NOT NULL,
	`update_user` VARCHAR(50) NOT NULL,
	`update_time` DATETIME NOT NULL,
	CONSTRAINT `PK_pc_sku_type` PRIMARY KEY (`code` ASC)
)

;

CREATE TABLE `pc_store_info`
(
	`uid` VARCHAR(50) NOT NULL,
	`code` VARCHAR(50) NOT NULL,
	`name` VARCHAR(50) NOT NULL,
	`type` VARCHAR(50) NOT NULL,
	`principal_name` VARCHAR(50) NOT NULL COMMENT '负责人姓名',
	`principal_phone` VARCHAR(50) NOT NULL COMMENT '负责人电话',
	`icon_url` VARCHAR(50) NOT NULL COMMENT '店铺图标链接地址',
	`status` VARCHAR(50) NOT NULL,
	`create_user` VARCHAR(50) NOT NULL,
	`create_time` DATETIME NOT NULL,
	`update_user` VARCHAR(50) NOT NULL,
	`update_time` DATETIME NOT NULL,
	CONSTRAINT `PK_pc_store_info` PRIMARY KEY (`code` ASC)
)
COMMENT = '店铺表'

;

CREATE TABLE `pc_store_status`
(
	`uid` VARCHAR(50) NOT NULL,
	`code` VARCHAR(50) NOT NULL,
	`name` VARCHAR(50) NOT NULL,
	`flag_enabled` INT NULL DEFAULT 0 COMMENT '0 可用 1 不可用',
	`create_user` VARCHAR(50) NOT NULL,
	`create_time` DATETIME NOT NULL,
	`update_user` VARCHAR(50) NOT NULL,
	`update_time` DATETIME NOT NULL,
	CONSTRAINT `PK_pc_store_status` PRIMARY KEY (`code` ASC)
)
COMMENT = '店铺状态表'

;

CREATE TABLE `pc_store_type`
(
	`uid` VARCHAR(50) NOT NULL,
	`code` VARCHAR(50) NOT NULL,
	`name` VARCHAR(50) NOT NULL,
	`flag_enabled` INT NULL DEFAULT 0 COMMENT '0 可用 1 不可用',
	`create_user` VARCHAR(50) NOT NULL,
	`create_time` DATETIME NOT NULL,
	`update_user` VARCHAR(50) NOT NULL,
	`update_time` DATETIME NOT NULL,
	CONSTRAINT `PK_pc_store_type` PRIMARY KEY (`code` ASC)
)
COMMENT = '店铺类型表'

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `pc_brand_info` 
 ADD INDEX `flag_enabled_index` (`flag_enabled` ASC)
;

ALTER TABLE `pc_category` 
 ADD INDEX `flag_enabled_index` (`flag_enabled` ASC)
;

ALTER TABLE `pc_label` 
 ADD INDEX `flag_enabled_index` (`flag_enabled` ASC)
;

ALTER TABLE `pc_product_info` 
 ADD INDEX `store_code_index` (`store_code` ASC)
;

ALTER TABLE `pc_product_info` 
 ADD INDEX `status_index` (`status` ASC)
;

ALTER TABLE `pc_product_info` 
 ADD INDEX `type_index` (`type` ASC)
;

ALTER TABLE `pc_product_info` 
 ADD INDEX `category_code_index` (`category_code` ASC)
;

ALTER TABLE `pc_product_info` 
 ADD INDEX `brand_code_index` (`brand_code` ASC)
;

ALTER TABLE `pc_product_pic` 
 ADD INDEX `product_code_index` (`product_code` ASC)
;

ALTER TABLE `pc_product_status` 
 ADD INDEX `flag_enabled_index` (`flag_enabled` ASC)
;

ALTER TABLE `pc_product_stock` 
 ADD CONSTRAINT `product_sku_uniq` UNIQUE (`product_code` ASC, `sku_code` ASC)
;

ALTER TABLE `pc_product_type` 
 ADD INDEX `flag_enabled_index` (`flag_enabled` ASC)
;

ALTER TABLE `pc_sku_info` 
 ADD INDEX `product_index` (`product_code` ASC)
;

ALTER TABLE `pc_sku_info` 
 ADD INDEX `type_index` (`type` ASC)
;

ALTER TABLE `pc_sku_info` 
 ADD INDEX `status_index` (`status` ASC)
;

ALTER TABLE `pc_sku_pic` 
 ADD INDEX `sku_code_index` (`sku_code` ASC)
;

ALTER TABLE `pc_sku_status` 
 ADD INDEX `flag_enabled_index` (`flag_enabled` ASC)
;

ALTER TABLE `pc_sku_type` 
 ADD INDEX `flag_enabled_index` (`flag_enabled` ASC)
;

ALTER TABLE `pc_store_info` 
 ADD INDEX `type_index` (`type` ASC)
;

ALTER TABLE `pc_store_info` 
 ADD INDEX `status_index` (`status` ASC)
;

ALTER TABLE `pc_store_info` 
 ADD INDEX `principal_phone` (`principal_phone` ASC)
;

ALTER TABLE `pc_store_status` 
 ADD INDEX `flag_enabled_index` (`flag_enabled` ASC)
;

ALTER TABLE `pc_store_type` 
 ADD INDEX `flag_enabled_index` (`flag_enabled` ASC)
;

SET FOREIGN_KEY_CHECKS=1 
;
