server:
  port: 9098
spring: 
  datasource:
    name: product
    url: jdbc:mysql://localhost:3306/cloud_oauth?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    initialSize: 1
    maxWait: 60000
    maxActive: 20
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    host: 192.168.99.100
    port: 6379
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.99.100:8010/eureka/
#安全认证配置
security:
  basic:
    enabled: false