spring:
  application:
    name: oauth2-demo
  redis:
    host: 192.168.99.100
    port: 6379
    database: 1
eureka:
  client:
    service-url:
      defaultZone: http://192.168.99.100:8010/eureka/

#logging.level.org.springframework.security: DEBUG

