server:
  port: 8010
eureka:
  instance:
    hostname: discovery
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://192.168.99.100:8010/eureka/