eureka:
  client:
    service-url:
      defaultZone: http://192.168.99.100:8010/eureka/
server:
  port: 8765
spring:
  application:
    name: service-hi
security:
  oauth2:
    client:
      id: client_2
      client-secret: 123456
      access-token-uri: http://192.168.99.100:9098/oauth/token
      grant-type: client_credentials,password
      scope: server
    resource:
      token-info-uri: http://192.168.99.100:9098/oauth/check_token
      user-info-uri: http://192.168.99.100:9098/user/current
    authorization:
      check-token-access: http://192.168.99.100:9098/oauth/check_token
