server:
  port: 8030
spring:
  profiles:
    active: beta
jwt:
  secret: systemcloudsecret
  header: Authorization
  expiration: 604800
  tokenHead: Bearer 
logging:
  level: 
    root: info
  config: classpath:logback.xml