spring:
  application:
    name: system-cloud
  datasource:
    name: product
    url: jdbc:mysql://localhost:3306/systemcenter?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    initialSize: 1
    maxWait: 60000
    maxActive: 20
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  # 缓存配置
  redis:
    host: 192.168.99.100
    port: 6379
    #clusterNodes: 
    #        - 127.0.0.1:7000
    #        - 127.0.0.1:7001
    #        - 127.0.0.1:7002
    #        - 127.0.0.1:7003
    #        - 127.0.0.1:7004
    #        - 127.0.0.1:7005
    expireSeconds: 120 
    #redis操作的超时时间
    commandTimeout: 10000
    pool: 
      maxActive: 5000 #最大连接数
      maxIdle: 30 #最大空闲连接数
      minIdle: 5 #最小空闲连接数
      maxWait: 3000  #获取连接最大等待时间 ms  #default -1
#header:凭证(校验的变量名), expire:有效期1天(单位:s), secret:秘钥(普通字符串)
jwt:
  secret: systemcloudsecret
  header: Authorization
  expiration: 604800
  tokenHead: Bearer 
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch.youran.persistence: ERROR
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.99.100:8010/eureka/